version: '3'
services:
  mysql-master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=mydb"
    volumes:
      - ./master/data:/var/lib/mysql
    links:
      - mysql-slave
    ports:
      - "33087:3306"
    restart: always
    hostname: mysql-master
  mysql-slave:
    build:
      context: ./
      dockerfile: slave/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=mydb"
    volumes:
      - ./slave/data:/var/lib/mysql
    ports:
      - "33088:3306"
    restart: always
    hostname: mysql-slave

